# Generated by Django 5.2 on 2025-04-22 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0002_vehiculo_activo_vehiculo_asignado_a_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('supervisor', models.CharField(max_length=100)),
                ('km_inicial', models.PositiveIntegerField()),
                ('km_final', models.PositiveIntegerField()),
                ('galones', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_por_galon', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo')),
            ],
        ),
    ]
