# Generated by Django 5.2 on 2025-04-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargacombustible',
            name='archivo_gps',
            field=models.FileField(blank=True, null=True, upload_to='gps/'),
        ),
        migrations.AddField(
            model_name='cargacombustible',
            name='archivo_reporte',
            field=models.FileField(blank=True, null=True, upload_to='reportes_combustible/'),
        ),
    ]
