# Generated by Django 5.2 on 2025-04-20 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('camioneta', 'Camioneta'), ('carro', 'Carro'), ('moto', 'Motor'), ('otro', 'Otro')], max_length=30)),
                ('documento_seguro', models.FileField(blank=True, null=True, upload_to='documentos_vehiculos/')),
                ('documento_matricula', models.FileField(blank=True, null=True, upload_to='documentos_vehiculos/')),
                ('licencia_operacion', models.FileField(blank=True, null=True, upload_to='documentos_vehiculos/')),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChequeoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('supervisor', models.CharField(max_length=100)),
                ('kilometraje', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='chequeos_vehiculos/')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo')),
            ],
        ),
    ]
