# Generated by Django 5.2 on 2025-04-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_vehiculo_rendimiento_estandar_alter_vehiculo_placa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('Carro', 'Carro'), ('Motor', 'Motor'), ('Camioneta', 'Camioneta'), ('SUV', 'SUV'), ('Camión', 'Camión'), ('Otro', 'Otro')], max_length=30),
        ),
    ]
