# Generated by Django 5.2 on 2025-04-20 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carnet', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=13)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Suspendido', 'Suspendido'), ('Ausente', 'Ausente'), ('Licencia', 'Licencia')], max_length=20)),
                ('ubicacion', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Fijo', 'Fijo'), ('Cubridor', 'Cubridor')], max_length=10)),
                ('turno', models.CharField(choices=[('Día', 'Día'), ('Noche', 'Noche')], max_length=10)),
                ('fecha_ingreso', models.DateField(default=datetime.date.today)),
                ('tipo_oficial', models.CharField(choices=[('Regular', 'Regular'), ('Jefe de Grupo', 'Jefe de Grupo'), ('VIP', 'VIP'), ('Supervisor', 'Supervisor'), ('Motorizado', 'Motorizado'), ('Otro', 'Otro')], max_length=20)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='archivos_oficiales/')),
            ],
        ),
    ]
