# Generated by Django 5.2 on 2025-04-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('serie', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('calibre', models.CharField(max_length=20)),
                ('licencia_digital', models.FileField(blank=True, null=True, upload_to='licencias_armas/')),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Asignada', 'Asignada'), ('Mantenimiento', 'Mantenimiento'), ('Baja', 'Baja')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
