# Generated by Django 5.2 on 2025-04-21 02:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arma',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arma',
            name='licencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='arma',
            name='marca',
            field=models.CharField(default='Desconocida', max_length=50),
        ),
        migrations.AlterField(
            model_name='arma',
            name='calibre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='arma',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Asignada', 'Asignada'), ('Mantenimiento', 'Mantenimiento'), ('Baja', 'Baja')], default='Disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='arma',
            name='tipo',
            field=models.CharField(choices=[('Pistola', 'Pistola'), ('Pistola Eléctrica', 'Pistola Eléctrica'), ('Escopeta', 'Escopeta'), ('Revólver', 'Revólver'), ('Rifle', 'Rifle'), ('Subfusil', 'Subfusil'), ('Carabina', 'Carabina'), ('Fusil de Asalto', 'Fusil de Asalto'), ('Otro', 'Otro')], max_length=50),
        ),
    ]
